name: Deploy Flask App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration & Deployment
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install required system packages
        run: |
          sudo apt update
          sudo apt install -y python3-full python3-venv python3-pip

      - name: Set up virtual environment and install requirements
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          .venv/bin/python -m pip install --upgrade pip --break-system-packages
          .venv/bin/python -m pip install -r requirements.txt --break-system-packages

      - name: Run Flask app
        run: |
          . .venv/bin/activate
          nohup .venv/bin/python app.py > output.log 2>&1 &
