name: Deploy Flask App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration & Deployment
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Python and tools are available
        run: |
          sudo apt update
          sudo apt install python3 python3-pip python3-venv -y
          python3 --version
          python3 -m pip --version

      - name: Set up virtual environment and install requirements
        run: |
          python3 -m venv venv
          source venv/bin/activate
          export PIP_BREAK_SYSTEM_PACKAGES=1
          python -m pip install --upgrade pip --break-system-packages
          python -m pip install -r requirements.txt --break-system-packages

      - name: Run Flask app
        run: |
          source venv/bin/activate
          nohup python app.py > output.log 2>&1 &
